config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'categories#index'
  resources :categories do
    resources :items, only: [:new, :create]
  end
  resources :items, only: [:edit, :update, :index, :destroy] do
    resources :item_taxes
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :items, :dependent => :destroy

  validates :name, presence: true, length: { in: 1..80 }, uniqueness: { case_sensitive: false }
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :category
  has_many :item_taxes, :dependent => :destroy

  validates :name, presence: true, length: {in: 1..80}, uniqueness: {scope: :category, message: "is already present in this category", case_sensitive: false}

  validates :rate, presence: true, numericality: { greater_than: 0}


  def total_tax
    self.item_taxes.map(&:amount).inject(:+) if self.item_taxes.any?
  end

  def grand_total
    rate + total_tax if total_tax.present?
  end
end

app/models/item_tax.rb
class ItemTax < ApplicationRecord
  belongs_to :item

  # enum tax_type: [:percentage, :value]

  validates :tax, :tax_name, :tax_type, presence: true
  validates :tax, numericality: {greater_than_or_equal_to: 0}
  validates :tax_name, length: { in: 1..80 }, uniqueness: {scope: :item, message: "is already present in this item", case_sensitive: false}
  validates :tax_type, inclusion: { in: %w(percentage value), message: "%{value} is not a valid tax type" }

  def amount
    self.tax_type == 'percentage' ? (self.tax.to_f/100)*self.item.rate : self.tax
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  before_action :set_category, only: [:edit, :update, :destroy]

  def new
    @category = Category.new
  end

  def index
    @categories = Category.all
  end

  def edit
  end

  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to categories_url, notice: 'Category was successfully created.' }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to categories_url, notice: 'Category was successfully Updated.' }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    respond_to do |format|
      if @category.destroy
        format.html { redirect_to categories_url, notice: 'Category was successfully Deleted.' }
      else
        format.html { redirect_to categories_url, notice: 'Category was not Deleted.' }
      end
    end

  end

  private

  def category_params
    params.require(:category).permit(:name)
  end

  def set_category
    @category = Category.find(params[:id])
  end
end

app/controllers/item_taxes_controller.rb
class ItemTaxesController < ApplicationController

  before_action :set_item, only: [:new, :create, :index]
  before_action :set_item_tax, only: [:destroy]

  def index
    @item_taxes = @item.item_taxes

  end

  def new
    @item_tax = @item.item_taxes.new
  end

  def create
    @item_tax = @item.item_taxes.new(item_tax_params)

    respond_to do |format|
      if @item_tax.save
        format.html { redirect_to item_item_taxes_url(@item), notice: 'Item Tax was successfully created.' }
      else
        format.html { render :new }
        format.json { render json: @item_tax.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    respond_to do |format|
      if @item_tax.destroy
        format.html { redirect_to item_item_taxes_url, notice: 'Item Tax  was successfully Deleted.' }
      else
        format.html { redirect_to item_item_taxes_url, notice: 'Item Tax was not Deleted.' }
      end
    end

  end

  private

  def set_item
    @item = Item.find params[:item_id]
  end

  def set_item_tax
    @item_tax = ItemTax.find params[:id]
  end

  def item_tax_params
    params.require(:item_tax).permit(:tax_name, :tax_type, :tax)
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  before_action :set_category, only: [:new, :create]
  before_action :set_item, only: [:destroy]

  def index
    @cat_ids = index_params[:categories_selection][:ids] if index_params[:categories_selection].present?
    @items = Item.where(category_id: index_params[:categories_selection][:ids]).preload(:category, :item_taxes) if @cat_ids.present?
  end

  def new
    @item = @category.items.new
  end

  def create
    @item = @category.items.new(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to item_item_taxes_url(@item), notice: 'Item was successfully created.' }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    respond_to do |format|
      if @item.destroy
        format.html { redirect_to items_url(categories_selection: {ids: params[:categories_selection][:ids]}), notice: 'Category was successfully Deleted.' }
      else
        format.html { redirect_to items_url(categories_selection: {ids: params[:categories_selection][:ids]}), notice: 'Category was not Deleted.' }
      end
    end
  end

  private

  def set_category
    @category = Category.find params[:category_id]
  end

  def set_item
    @item = Item.find params[:id]
  end

  def item_params
    params.require(:item).permit(:name, :rate)
  end

  def index_params
    params.permit(categories_selection: [ids: []])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/item_taxes_helper.rb
module ItemTaxesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/categories/_form.html.erb
<div class="row">
<%= simple_form_for(category, html: {class: 'col-md-6'}) do |f| %>
    <%= f.error_notification %>
    <%= f.input :name , :input_html => { :size => 80, :maxlength => 80}%>
      <br/>
    <%= f.button :submit, class: "btn btn-success", value: 'Save' %>
    <%= link_to('Cancel' , categories_path, class: "btn btn-link") %>
<% end %>
</div>

app/views/categories/edit.html.erb
<% content_for :header do %>
    Edit Category
<% end %>
<%= render 'form', category: @category %>

app/views/categories/index.html.erb
<% content_for :header do %>
    Categories
<% end %>
<%= link_to 'Add Category', new_category_path, class: "btn btn-success" %>
<% if @categories.any? %>
<%= simple_form_for :categories_selection, url: items_path, method: :get do |f| %>
<table class="table table-striped">
  <tr>
    <th></th>
    <th>Name</th>
    <th>Action</th>
  </tr>
  <% @categories.each do |cat| %>
      <tr>
        <td><%= f.check_box :ids, { multiple: true }, cat.id, false %></td>
        <td><%= cat.name.upcase %></td>
        <td>
          <%= link_to 'Edit', edit_category_path(cat), class: "btn btn-sm btn-primary"%>
          <%= link_to 'Delete', category_path(cat), method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-sm btn-danger'%>
          <%= link_to 'Add Item', new_category_item_path(cat), class: "btn btn-sm btn-success"%>
          <%= link_to 'Show Items', items_path(categories_selection: {ids: [cat.id]}), class: "btn btn-sm btn-info"%>
        </td>
      </tr>
  <% end %>
</table>
    <%= f.submit class: "btn btn-info", value: 'Show items of selected categories'%>
<% end %>
<% else %>
    <div class="well" style="margin: 10px;">No Categories found</div>
<% end %>

app/views/categories/new.html.erb
<% content_for :header do %>
    Create Category
<% end %>
<%= render 'form', category: @category %>

app/views/item_taxes/_form.html.erb
<div class="row">
  <%= simple_form_for(item_tax, html: {class: 'col-md-6'}, :url => item_item_taxes_path) do |f| %>
      <%= f.error_notification %>
      <%= f.input :tax_name, :input_html => { :size => 80, :maxlength => 80}%>
      <br/>
      <%= f.input :tax_type, :collection => { 'Percentage' => :percentage, 'Value' => :value}, :include_blank => false %>
      <br/>
      <%= f.input :tax, :input_html => {value: number_with_precision(f.object.tax, precision: 2)}%>
      <br/>
      <%= f.button :submit, class: "btn btn-success", value: 'Save' %>
      <%= link_to('Cancel' , item_item_taxes_path, class: "btn btn-link") %>
  <% end %>
</div>

app/views/item_taxes/index.html.erb
<% content_for :header do %>
    <%= @item.name.upcase %> Taxes
<% end %>
    <table class="table table-striped">
      <tr>
        <th>Name</th>
        <th>Value</th>
        <th>Type</th>
        <th>Amount</th>
        <th>Action</th>
      </tr>
      <% @item_taxes.each do |item_tax| %>
          <tr>
            <td><%= item_tax.tax_name.upcase %></td>
            <td><%= item_tax.tax %></td>
            <td><%= item_tax.tax_type %></td>
            <td><%= item_tax.amount %></td>
            <td>
              <%= link_to 'Delete', item_item_tax_path(@item, item_tax), method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-sm btn-danger'%>
            </td>
          </tr>
      <% end %>
    </table>
    <%= link_to 'Add Tax', new_item_item_tax_path(@item), class: "btn btn-success"%>
    <%= link_to "#{@item.category.name} items list", items_path(categories_selection: {ids: [@item.category.id]}), class: "btn btn-link"%>
<hr/>
<div class="col-md-3">
  <h4>Item Total Amount</h4>
<table class="table table-condensed table-bordered">
  <tr>
    <td><b>Rate : </b></td>
    <td><%= @item.rate %></td>
  </tr>
  <tr>
    <td><b>Total Taxes : </b></td>
    <td><%= @item.total_tax %></td>
  </tr>
  <tr>
    <td><b>Grand Total</b></td>
    <td><b><%= @item.grand_total %></b></td>
  </tr>

</table>
</div>

app/views/item_taxes/new.html.erb
<% content_for :header do %>
    Create Item Tax for <%= @item.name.upcase %>
<% end %>
<%= render 'form', item_tax: @item_tax %>

app/views/items/_form.html.erb
<div class="row">
  <%= simple_form_for(item, html: {class: 'col-md-6'}, :url => category_items_path) do |f| %>
      <%= f.error_notification %>
      <%= f.input :name , :input_html => { :size => 80, :maxlength => 80}%>
      <br/>
      <%= f.input :rate , :input_html => {value: number_with_precision(f.object.rate, precision: 2)}%>
      <br/>
      <%= f.button :submit, class: "btn btn-success", value: 'Save' %>
      <%= link_to('Cancel' , categories_path, class: "btn btn-link") %>
  <% end %>
</div>

app/views/items/index.html.erb
<% content_for :header do %>
    Items List
<% end %>

<% if @items.present? %>
        <table class="table table-striped">
          <tr>
            <th>Name</th>
            <th>Category</th>
            <th>Rate</th>
            <th>Total Tax</th>
            <th>Grand Total</th>
            <th>Action</th>
          </tr>
          <% @items.each do |item| %>
              <tr>
                <td><%= item.name.upcase %></td>
                <td><%= item.category.name.upcase %></td>
                <td><%= item.rate %></td>
                <td><%= item.total_tax %></td>
                <td><%= item.grand_total %></td>
                <td>
                  <%= link_to('Manage Taxes', item_item_taxes_path(item), class: "btn btn-link") %>
                  <%= link_to 'Delete', item_path(item, categories_selection: {ids: @cat_ids}), method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-sm btn-danger'%>
                </td>
              </tr>
          <% end %>
        </table>
<% else %>
    <div class="well" style="margin: 10px;">No Items found</div>
<% end %>
<br/>
<%= link_to('Back to all categories', categories_path, class: "btn btn-link") %>

app/views/items/new.html.erb
<% content_for :header do %>
    Create Item for <%= @category.name %>
<% end %>
<%= render 'form', item: @item %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <h3>Shop</h3>
    </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to('All Categories', categories_path, class: "nav-link") %></li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Shop</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div class="container-fluid">

    <%= render 'layouts/navbar' %>

    <h3><%= content_for?(:header) ? yield(:header) : "Shop" %></h3>

    <div>
      <% if flash[:notice] %>
          <div class="alert alert-success"><%= notice.html_safe %></div>
      <% end %>
      <% if flash[:alert] %>
          <div class="alert alert-danger"><%= alert.html_safe %></div>
      <% end %>
      <% if flash[:message] %>
          <div class="alert alert-info"><%= flash[:message].html_safe %></div>
      <% end %>
    </div>

    <%= yield %>
  </div>
  </body>
</html>